import os

GOOGLE_MAPS_API_URL = os.environ["GOOGLE_MAPS_API_URL"]
GOOGLE_MAPS_API_KEY = os.environ["GOOGLE_MAPS_API_KEY"]

TARGOMO_API_URL = os.environ["TARGOMO_API_URL"]
TARGOMO_API_KEY = os.environ["TARGOMO_API_KEY"]

NOMINATIM_API_URL = os.environ["NOMINATIM_API_URL"]